# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('address_line_1', models.CharField(max_length=60)),
                ('address_line_2', models.CharField(max_length=60)),
                ('address_line_3', models.CharField(max_length=60)),
                ('address_line_4', models.CharField(max_length=60)),
                ('post_code', models.CharField(max_length=12)),
                ('email_address', models.EmailField(max_length=254)),
                ('stripe_id', models.CharField(default='', max_length=40)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.Merchandise')),
            ],
        ),
    ]
