# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='address_line_4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
