# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
