# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_subject_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
