# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_to_guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howto',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
