# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_name',
            field=models.CharField(default='test', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
