# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_public_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
