# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_auto_20170426_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandise',
            options={'verbose_name_plural': 'Merchandise'},
        ),
    ]
